version: 0.0.0.{build}

clone_depth: 1

image: Ubuntu2004

install:
  - 'pushd $HOME'
  - 'wget https://github.com/Kagami/nacl_sdk/archive/refs/heads/master.zip -O nacl_sdk.zip'
  - 'unzip nacl_sdk.zip'
  - 'cd nacl_sdk-master'
  - 'source $HOME/venv2.7/bin/activate'
  - './naclsdk update'
  - 'export NACL_SDK_ROOT=$HOME/nacl_sdk-master/pepper_49'
  - 'popd'

before_build:
  - 'git submodule update --init --recursive'

build_script:
  - 'make -j$(nproc)'

after_build:
  - 'zip -r moonlight-chrome.zip . -x ".git/*"'
  - 'appveyor PushArtifact moonlight-chrome.zip'

deploy: off
